name: Selenium test CI pipeline
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: selcuktemizsoy/selenium-demo:latest
